# Generated by Django 4.1.7 on 2023-03-22 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('time_on_minute', models.IntegerField()),
            ],
            options={
                'verbose_name': 'RegionModel',
                'verbose_name_plural': 'RegionModels',
            },
        ),
        migrations.CreateModel(
            name='TelegramUserModel',
            fields=[
                ('chat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.regionmodel')),
            ],
            options={
                'verbose_name': 'TelegramUser',
                'verbose_name_plural': 'TelegramUsers',
            },
        ),
    ]
