# Generated by Django 4.1.7 on 2023-03-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_telegramusermodel_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bomdod', models.TimeField()),
                ('quyosh', models.TimeField()),
                ('peshin', models.TimeField()),
                ('asr', models.TimeField()),
                ('shom', models.TimeField()),
                ('xufton', models.TimeField()),
            ],
            options={
                'verbose_name': 'TimeModel',
                'verbose_name_plural': 'TimeModels',
            },
        ),
    ]
