# Generated by Django 4.1.7 on 2023-03-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_timemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timemodel',
            name='asr',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='bomdod',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='peshin',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='quyosh',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='shom',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='xufton',
            field=models.TimeField(null=True),
        ),
    ]
