# Generated by Django 4.1.7 on 2023-03-24 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_regionmodel_solat_times'),
    ]

    operations = [
        migrations.CreateModel(
            name='QazoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bomdod', models.IntegerField(default=0)),
                ('quyosh', models.IntegerField(default=0)),
                ('peshin', models.IntegerField(default=0)),
                ('asr', models.IntegerField(default=0)),
                ('shom', models.IntegerField(default=0)),
                ('xufton', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'QazoModel',
                'verbose_name_plural': 'QazolarModels',
            },
        ),
        migrations.AlterModelOptions(
            name='regionmodel',
            options={'verbose_name': 'RegionModel', 'verbose_name_plural': 'RegionsModels'},
        ),
        migrations.AlterModelOptions(
            name='timemodel',
            options={'verbose_name': 'TimeModel', 'verbose_name_plural': 'TimesModels'},
        ),
        migrations.AddField(
            model_name='telegramusermodel',
            name='qazo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.qazomodel'),
        ),
    ]
